#!/bin/bash
ROOT=$(dirname $(readlink -f $BASH_SOURCE))/..
. $ROOT/main/environment
# setup nimbus since cat pod cleanup needs to use stable
# version of nimbus. requirement same as deploy testbed
. $ROOT/scripts/nimbus/setup
export PYTHONPATH=$ROOT/main:$PYTHONPATH
$PYTHON $ROOT/scripts/catPODCleanup.py
