#!/bin/bash
ROOT=$(dirname $(readlink -f $(which "$0")))/..
. $ROOT/main/environment
OPTION="$@"
if [ "$OPTION" != "${OPTION/-debug/}" ]; then
  export VDNET_DEBUG=1
  $PERL -d $ROOT/main/vdNet.pl `echo $OPTION | sed -e "s/-\+debug//"`
else
  $PERL $ROOT/scripts/./keysDBOnWiki.pl
fi
