#!/bin/bash
ROOT=$(dirname $(readlink -f $(which "$0")))/..
. $ROOT/main/environment
. $ROOT/scripts/nimbus/setup
# use "$@" to preserve the qoutes given in the command line
# otherwise, value of --vdnetOptions will be treated as command line
# parameters of offsutVDNetWorkload.py
$PYTHON $ROOT/main/offsutVDNetWorkload.py "$@"
