#!/bin/bash

# This module invokes VerificationUnitTest.pl which contains unit tests
# for verification operators for different examples of user/server data.
#
# Usage:
# ./vdnet_verification

ROOT=$(dirname $(readlink -f $(which "$0")))/..
. $ROOT/main/environment
. $ROOT/scripts/nimbus/setup
$PERL $ROOT/scripts/unitTests/VerificationUnitTest.pl
