#!/bin/bash
ROOT=$(dirname $(readlink -f $(which "$0")))/..

PERLVERSION=5.8.8
PERLDIR=perl58
PERLBASE=/build/toolchain/lin32/perl-$PERLVERSION
STAFBASE=/build/toolchain/lin32/staf-3.4.1

PERL=$PERLBASE/bin/perl

export PERLLIB=$STAFBASE/lib/perl58:$STAFBASE/bin
export PATH=$STAFBASE/lib/$PERLDIR:$STAFBASE/bin:/build/toolchain/lin32/python-2.7.9-openssl1.0.1k/bin:$PATH
export LD_LIBRARY_PATH=$PERLBASE/lib/$PERLVERSION/i686-linux-thread-multi/CORE:$STAFBASE/lib:$STAFBASE/lib/perl58
export PYTHONPATH=/build/toolchain/noarch/xlwt-0.7.4/lib/python2.6/site-packages
PERL=$PERLBASE/bin/perl
$PERL $ROOT/scripts/generateTDS.pl "$@"
