#!/bin/bash
if [ -z "$NIMBUS_BASE" ]; then
   NIMBUS_BASE="/mts/git"
fi
. $NIMBUS_BASE/nimbus/config
ROOT=$(dirname $(readlink -f $(which "$0")))/..
exec $NIMBUS_BASE/bin/rbvmomi $ROOT/nimbus/nimbus-ovfdeploy.rb "$@"
