AccessConfigureConsole:
    Product: "NSXTransformers"
    Category: "Edge"
    Component: "NSXEdgeInstallation"
    Developer: "sucheta"
    Version: "2"
    ExpectedResult: "PASS"
    Status: "Execution Ready"
    AutomationLevel: "Automated"
    FullyAutomatable: "Y"
    TestcaseLevel: "Functional"
    TestcaseType: "Functional"
    Duration: '5'
    Tags: 'cat-01'
    Partnerfacing: "N"
    Priority: "P0"
    QCPath: "/NSXTransformers/EDGE/Install"
    TestName: "Verify Edge Details Via console "
    Summary: "Verify Installed Edge details via console"
    Procedure: "1. Connect to Esxi Server .
                2. Go to Edge console.
                3. Login using the Configure mode.
                4. Compare the list of all available commands at Configure console."
    ExpectedResult: "Verify all details should be match as per RTQA mention "

    TestbedSpec: *L3_ESX_TOPOLOGY_01


    WORKLOADS:
        Sequence:
             - ['VerifyWithDefaultLoginConfigureModeAndListCommands']
             - ['VerifyWithValidLoginConfigureModeAndListCommands']
             - ['VerifyWithInvalidLoginConfigureModeAndListCommands']

        VerifyWithDefaultLoginConfigureModeAndListCommands:
            Type: Gateway
            TestGateway: 'nsxedge.[1]'
            execution_type: 'cli'
            get_supported_commands_configure_mode:
                'supported_commands[?]file_equal_to': "VDNetLib/TestData/Edge/list_command_configure_mode"

        VerifyWithValidLoginConfigureModeAndListCommands:
            Type: Gateway
            TestGateway: 'nsxedge.[1]'
            execution_type: 'cli'
            password: 'C@shc0w12345'
            get_supported_commands_configure_mode:
                'supported_commands[?]file_equal_to': "VDNetLib/TestData/Edge/list_command_configure_mode"

        VerifyWithInvalidLoginConfigureModeAndListCommands:
            Type: Gateway
            TestGateway: 'nsxedge.[1]'
            execution_type: 'cli'
            password: 'incorrect_password'
            get_supported_commands_configure_mode:
                'result[?]equal_to': False
