HardwareConfigurationOfEdgeNode:
    Product: "NSXTransformers"
    Category: "Edge"
    Component: "EdgeHardwareConfiguration"
    Developer: "sureshkoli"
    Version: "2"
    ExpectedResult: "PASS"
    Status: "Execution Ready"
    AutomationLevel: "Automated"
    FullyAutomatable: "Y"
    TestcaseLevel: "Functional"
    TestcaseType: "Functional"
    Duration: '5'
    Tags: 'cat-01'
    Partnerfacing: "N"
    Priority: "P0"
    QCPath: "/NSXTransformers/EDGE/Install"
    TestName: "Verify Compact Edge Hardware configuration "
    Summary: "Verify Installed Compact Edge hardware configuration"
    Procedure: "1. Installed Edge via OVF.
                2. Deploy Compact size of EdgeNode.
                3. Verify configuration details of Edge"
    ExpectedResult: "Verify configuration details should get as per size selected "

    TestbedSpec: *L3_ESX_TOPOLOGY_01


    WORKLOADS:
        Sequence:
             - ['VerifyCpuCount']
             - ['VerifyNicCount']
             - ['VerifyDiskCount']
             - ['VerifyMemorySize']
             - ['VerifyNic1Type']
             - ['VerifyNic2Type']
             - ['VerifyNic3Type']
             - ['VerifyDisk1Size']
             - ['VerifyMaxCpuUsage']
             - ['VerifyMaxMemoryUsage']

        VerifyCpuCount:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            cpu_count:
                'expected_cpu_count[?]equal_to': 1

        VerifyMaxMemoryUsage:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            max_mem_usage:
                'expected_max_mem_usage[?]equal_to': '512 MB'

        VerifyMaxCpuUsage:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            max_cpu_usage:
                'expected_max_cpu_usage[?]equal_to': '2128 MHz'

        VerifyNicCount:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            nic_count:
                'expected_nic_count[?]equal_to': 3

        VerifyNic1Type:
            Type: VM
            TestVM: 'nsxedge.[1]'
            vnic_index: '1'
            execution_type: 'cli'
            nic_type:
                'expected_nic_type[?]equal_to': 'VirtualVmxnet3'

        VerifyNic2Type:
            Type: VM
            TestVM: 'nsxedge.[1]'
            vnic_index: '2'
            execution_type: 'cli'
            nic_type:
                'expected_nic_type[?]equal_to': 'VirtualVmxnet3'

        VerifyNic3Type:
            Type: VM
            TestVM: 'nsxedge.[1]'
            vnic_index: '3'
            execution_type: 'cli'
            nic_type:
                'expected_nic_type[?]equal_to': 'VirtualVmxnet3'

        VerifyDisk1Size:
            Type: VM
            TestVM: 'nsxedge.[1]'
            disk_index: '1'
            execution_type: 'cli'
            disk_size:
                'expected_disk_size[?]equal_to': '500 MB'

        VerifyDiskCount:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            virtual_disk_count:
                'expected_virtual_disk_count[?]equal_to': 1

        VerifyMemorySize:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            mem_size:
                'expected_mem_size[?]equal_to': '512 MB'
