HardwareConfigurationOfEdgeNode:
    Product: "NSXTransformers"
    Category: "Edge"
    Component: "EdgeHardwareConfiguration"
    Developer: "sureshkoli"
    Version: "2"
    ExpectedResult: "PASS"
    Status: "Execution Ready"
    AutomationLevel: "Automated"
    FullyAutomatable: "Y"
    TestcaseLevel: "Functional"
    TestcaseType: "Functional"
    Duration: '5'
    Tags: 'cat-01'
    Partnerfacing: "N"
    Priority: "P0"
    QCPath: "/NSXTransformers/EDGE/Install"
    TestName: "Verify Hardware configuration "
    Summary: "Verify Installed Edge hardware configuration"
    Procedure: "1. Installed Edge via OVF.
                2. Deploy All size of EdgeNode.
                3. Verify configuration details of all Edge"
    ExpectedResult: "Verify configuration details should get as per size selected "

    TestbedSpec: *L3_ESX_TOPOLOGY_01


    WORKLOADS:
        Sequence:
             - ['VerifyCpuCount']
             - ['VerifyNicCount']
             - ['VerifyDiskCount']
             - ['VerifyMemorySize']
             - ['VerifyNic1Type']
             - ['VerifyDisk1Size']
             - ['VerifyMaxCpuUsage']
             - ['VerifyMaxMemoryUsage']

        VerifyCpuCount:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            cpu_count:
                'expected_cpu_count[?]not_equal_to': 3

        VerifyMaxMemoryUsage:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            max_mem_usage:
                'expected_max_mem_usage[?]not_equal_to': '1024 MB'

        VerifyMaxCpuUsage:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            max_cpu_usage:
                'expected_max_cpu_usage[?]not_equal_to': '2000 MHz'

        VerifyNicCount:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            nic_count:
                'expected_nic_count[?]not_equal_to': 5

        VerifyNic1Type:
            Type: VM
            TestVM: 'nsxedge.[1]'
            vnic_index: '1'
            execution_type: 'cli'
            nic_type:
                'expected_nic_type[?]not_equal_to': 'VirtualVmxnet1'

        VerifyDisk1Size:
            Type: VM
            TestVM: 'nsxedge.[1]'
            disk_index: '1'
            execution_type: 'cli'
            disk_size:
                'expected_disk_size[?]not_equal_to': '1000 MB'

        VerifyDiskCount:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            virtual_disk_count:
                'expected_virtual_disk_count[?]not_equal_to': 2

        VerifyMemorySize:
            Type: VM
            TestVM: 'nsxedge.[1]'
            execution_type: 'cli'
            mem_size:
                'expected_mem_size[?]not_equal_to': '1024 MB'
